export const colors = {
  border: 'hsl(var(--border))',
  input: 'hsl(var(--input))',
  ring: 'hsl(var(--ring))',
  background: 'hsl(var(--background))',
  foreground: 'hsl(var(--foreground))',
  primary: {
    50: 'hsl(var(--primary-50))',
    '50-foreground': 'hsl(var(--primary-50-foreground))',
    100: 'hsl(var(--primary-100))',
    '100-foreground': 'hsl(var(--primary-100-foreground))',
    200: 'hsl(var(--primary-200))',
    '200-foreground': 'hsl(var(--primary-200-foreground))',
    300: 'hsl(var(--primary-300))',
    '300-foreground': 'hsl(var(--primary-300-foreground))',
    400: 'hsl(var(--primary-400))',
    '400-foreground': 'hsl(var(--primary-400-foreground))',
    DEFAULT: 'hsl(var(--primary))',
    foreground: 'hsl(var(--primary-foreground))',
    600: 'hsl(var(--primary-600))',
    '600-foreground': 'hsl(var(--primary-600-foreground))',
    700: 'hsl(var(--primary-700))',
    '700-foreground': 'hsl(var(--primary-700-foreground))',
    800: 'hsl(var(--primary-800))',
    '800-foreground': 'hsl(var(--primary-800-foreground))',
    900: 'hsl(var(--primary-900))',
    '900-foreground': 'hsl(var(--primary-900-foreground))',
    950: 'hsl(var(--primary-950))',
    '950-foreground': 'hsl(var(--primary-950-foreground))',
  },
  secondary: {
    DEFAULT: 'hsl(var(--secondary))',
    foreground: 'hsl(var(--secondary-foreground))',
  },
  destructive: {
    DEFAULT: 'hsl(var(--destructive))',
    foreground: 'hsl(var(--destructive-foreground))',
  },
  muted: {
    DEFAULT: 'hsl(var(--muted))',
    foreground: 'hsl(var(--muted-foreground))',
  },
  accent: {
    DEFAULT: 'hsl(var(--accent))',
    foreground: 'hsl(var(--accent-foreground))',
  },
  popover: {
    DEFAULT: 'hsl(var(--popover))',
    foreground: 'hsl(var(--popover-foreground))',
  },
  card: {
    DEFAULT: 'hsl(var(--card))',
    foreground: 'hsl(var(--card-foreground))',
  },
};
